# Generated by Django 6.0.4 on 2026-04-17 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_PROGRESSO', 'Em Progresso'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('story_points', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
