# Generated by Django 6.0.4 on 2026-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'A Fazer'), ('EM_PROGRESSO', 'Em Progresso'), ('PRONTO', 'Pronto'), ('ENTREGUE', 'Entregue')], default='A_FAZER', max_length=12),
        ),
    ]
